
package frc.robot.commands.swervedrive;
import edu.wpi.first.wpilibj2.command.Command;

import frc.robot.subsystems.swervedrive.Intake;

public class PositionArm extends Command {
       
    private final Intake m_intake;
    private final int m_position;
 
    public PositionArm(Intake subsystem, int position) {

        m_intake = subsystem;
        m_position = position;
        addRequirements(m_intake);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
           m_intake.position(m_position);
     }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}

